Whisper_AI_Configurations:
  Model_Name: "openai/whisper-large-v3"
  Hugging_Face_Token: False
  Maximum_Token_Generation: 200
  Language_Selection: "english"

Google_Flan_T5:
  Model_Name: "google/flan-t5-base"
  Hugging_Face_Token: False
  Maximum_Token_Generation:
    Short_Output:
      Minimum_Length: 30
      Maximum_Length: 100
    Medium_Output:
      Minimum_Length: 100
      Maximum_Length: 200
    Large_Output:
      Minimum_Length: 500
      Maximum_Length: 1024

Facebook_Bart_CNN:
  Model_Name: "facebook/bart-large-cnn"
  Model_Task: "summarization"
  Hugging_Face_Token: False
  Minimum_Length: 30
  Maximum_Length: 300

Phi4_Language_Model:
  Model_Name: "microsoft/Phi-4-mini-instruct"
  Model_Task: "text-generation"
  Hugging_Face_Token: False
  Maximum_New_Token: 32768
  Temperature: 0.7
  Top_P: 0.95

Gliner_Model:
  Model_Name: "gliner-community/gliner_large-v2.5"
  Maximum_Length: 1000
  Labels:
    - Persons
    - Organization
    - Location
