Data_Processing_Pipeline:
  Folder_Tree:
    Temp_Zip: "dev-clean.tar.gz"
    Temp_Unzip: "libspeech"
    Raw_Data: "raw_libspeech"
  Source_Download: "http://www.openslr.org/resources/12/dev-clean.tar.gz"
  Corpus_Structure: "LibriSpeech/dev-clean"
  Maximum_Batch_Size: 5